
import java.awt.Image;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Stroescu Andrei
 */
public class ReduceriAutomobil extends javax.swing.JFrame {
Connection conn;
ResultSet rs;
PreparedStatement pst;
String ImgPath=null;
    /**
     * Creates new form ReduceriAutomobil
     */

public Connection getConnection(){
        Connection conn=null;
        
        try {
            conn=DriverManager.getConnection("jdbc:mysql://localhost/masini","root","");
            //JOptionPane.showMessageDialog(null,"Conectat!");
            return conn;
        } catch (SQLException ex) {
            Logger.getLogger(AdaugatiAutomobil.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null,"Deconectat!");
            return null;
        }
    }


    public ReduceriAutomobil() {
       super("Reduceri Automobile");
        initComponents();
        conn=javaconect.getConnection();
        Show_Products_In_JTable();
        AdaugareFisierTxt1();
        
    }
    //Adaugare in fisier
    public void AdaugareFisierTxt1(){
        String filePath="C:\\Users\\stroe\\Documents\\NetBeansProjects\\InchirieredeAutomobile\\reducerimasini.txt";
        File file=new File(filePath);
        try {
            FileWriter fw=new FileWriter(file);
            BufferedWriter bw=new BufferedWriter(fw);
            
            for(int i=0;i<pretredus.getRowCount();i++){//linie
                for(int j=0;j<pretredus.getColumnCount()-1;j++){//coloana
                    bw.write(pretredus.getValueAt(i, j).toString()+" ");
                }
                bw.newLine();
            }
            
            bw.close();
            fw.close();
            
        } catch (IOException ex) {
            Logger.getLogger(AdaugatiAutomobil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    //Redimensionare imagine
    public ImageIcon ResizeImage(String ImgPath,byte[] pic){
        ImageIcon myImage=null;
        
        if(ImgPath!=null){
            myImage=new ImageIcon(ImgPath);
        }else{
            myImage=new ImageIcon(pic);
        }
        Image img=myImage.getImage();
        Image img2=img.getScaledInstance(imagine.getWidth(), imagine.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }
      //Verificati campurile de intrare
    
    public boolean checkInputs(){
        if(        ID.getText()==null
                || marca.getText()==null
                || model.getText()==null
                || anfabricatie.getText()==null
                || culoare.getText()==null
                || descriere.getText()==null
                || pretzi.getText()==null
                || pretzi1.getText()==null
                || tractiune.getSelectedItem()==null
                || consum.getText()==null
                || imagine.getIcon()==null
                ){
                    return false;
              }else{
                    try{
                        Float.parseFloat(pretzi.getText());
                         Float.parseFloat(pretzi1.getText());
                        return true;
                    }catch(Exception ex){
                        return false;
                    }
        }   
        
    }
    
    //resetare campuri 
     public void clearFields(){
        ID.setText(null);
        marca.setText(null);
        model.setText(null);
        anfabricatie.setText(null);
        culoare.setText(null);
        descriere.setText(null);
        pretzi.setText(null);
        pretzi1.setText(null);
        consum.setText(null);
        imagine.setIcon(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pretredus = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        model = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        anfabricatie = new javax.swing.JTextField();
        culoare = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriere = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        pretzi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        consum = new javax.swing.JTextField();
        poza = new javax.swing.JLabel();
        imagine = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pretzi1 = new javax.swing.JTextField();
        adaugareImagine = new javax.swing.JButton();
        adaugate = new javax.swing.JButton();
        tractiune = new javax.swing.JComboBox();
        actualizati = new javax.swing.JButton();
        sterge = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        pretredus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Masina", "Marca", "Model", "AnFabricatie", "Culoare", "Descriere", "Pret/zi", "Pret/zi redus", "Tractiune", "Consum", "Imagine"
            }
        ));
        pretredus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pretredusMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(pretredus);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(25, 101, 148));
        jLabel1.setText("Reduceri Si Preturi Promotionale");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagini/Back_20px.png"))); // NOI18N
        jButton1.setText("Inapoi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagini/Close Window_20px.png"))); // NOI18N
        jButton2.setText("Iesire");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID Masina");

        ID.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ID.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Marca");

        marca.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        marca.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Model");

        model.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        model.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("An Fabricatie");

        anfabricatie.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        anfabricatie.setPreferredSize(new java.awt.Dimension(6, 25));

        culoare.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        culoare.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Culoare");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Descriere");

        descriere.setColumns(20);
        descriere.setRows(5);
        jScrollPane1.setViewportView(descriere);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Pret/zi");

        pretzi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pretzi.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Tracțiune");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Consum/100km");

        consum.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        consum.setPreferredSize(new java.awt.Dimension(6, 25));

        poza.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        poza.setText("Poza");

        imagine.setBackground(new java.awt.Color(255, 255, 0));
        imagine.setForeground(new java.awt.Color(153, 204, 0));
        imagine.setOpaque(true);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Pret Redus");

        pretzi1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        pretzi1.setPreferredSize(new java.awt.Dimension(6, 25));

        adaugareImagine.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adaugareImagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagini/Add_20px.png"))); // NOI18N
        adaugareImagine.setText("Alegeți Imagine");
        adaugareImagine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaugareImagineActionPerformed(evt);
            }
        });

        adaugate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adaugate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagini/Enter_20px.png"))); // NOI18N
        adaugate.setText("Adaugare");
        adaugate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaugateActionPerformed(evt);
            }
        });

        tractiune.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "4x2Fata", "4x2Spate", "4x4" }));

        actualizati.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        actualizati.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagini/Update_20px.png"))); // NOI18N
        actualizati.setText("Actualizare");
        actualizati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizatiActionPerformed(evt);
            }
        });

        sterge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sterge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagini/Delete_20px.png"))); // NOI18N
        sterge.setText("Ștergere");
        sterge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stergeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(poza))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anfabricatie, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pretzi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(model, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(culoare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(consum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(marca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adaugareImagine, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(imagine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pretzi1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tractiune, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adaugate)
                        .addGap(70, 70, 70)
                        .addComponent(actualizati)
                        .addGap(69, 69, 69)
                        .addComponent(sterge)
                        .addGap(73, 73, 73)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(anfabricatie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(culoare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(pretzi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(pretzi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tractiune, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(consum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poza)
                            .addComponent(imagine, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adaugareImagine)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adaugate)
                    .addComponent(actualizati)
                    .addComponent(sterge)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(45, 45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        Meniu frm=new Meniu();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void adaugareImagineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaugareImagineActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));

        FileNameExtensionFilter filter=new FileNameExtensionFilter("*.image","jpg","png");
        file.addChoosableFileFilter(filter);
        int result=file.showSaveDialog(null);
        if(result==JFileChooser.APPROVE_OPTION){
            File selectedFile=file.getSelectedFile();
            String path=selectedFile.getAbsolutePath();
            imagine.setIcon(ResizeImage(path,null));
            ImgPath=path;
        }else{
            System.out.println("Nu ați selectat imaginea!");
        }
    }//GEN-LAST:event_adaugareImagineActionPerformed

    private void adaugateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaugateActionPerformed
        // TODO add your handling code here:
        if(ImgPath!=null && checkInputs()){
            try {
                Connection conn=getConnection();
                PreparedStatement ps=conn.prepareStatement("INSERT INTO reduceri(ID_Masina, Marca, Model, An_Fabricatie, Culoare, Descriere, Pret_Zi, Pret_Redus, Tractiune, Consum, Poza)"
                    + "values(?,?,?,?,?,?,?,?,?,?,?)");
                ps.setString(1, ID.getText());
                ps.setString(2, marca.getText());
                ps.setString(3, model.getText());
                ps.setString(4, anfabricatie.getText());
                ps.setString(5, culoare.getText());
                ps.setString(6, descriere.getText());
                ps.setString(7, pretzi.getText());
                ps.setString(8, pretzi1.getText());
                ps.setString(9, (String) tractiune.getSelectedItem());
                ps.setString(10, consum.getText());

                InputStream img = new FileInputStream(new File(ImgPath));
                ps.setBlob(11, img);
                ps.executeUpdate();
                Show_Products_In_JTable();
                JOptionPane.showMessageDialog(null, "Datele au fost introduse!");
                clearFields();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Unul sau mai multe câmpuri sunt goale!");
        }
    }//GEN-LAST:event_adaugateActionPerformed

    private void pretredusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pretredusMouseClicked
        // TODO add your handling code here:
        int index=pretredus.getSelectedRow();
        ShowItem(index);
    }//GEN-LAST:event_pretredusMouseClicked

    private void actualizatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizatiActionPerformed
        // TODO add your handling code here:
        if(checkInputs() && ID.getText()!=null){
            String UptadeQuery=null;
            PreparedStatement ps=null;
            Connection conn=getConnection();

            //actualizare fara imagine
            if(ImgPath==null){
                try {
                    UptadeQuery="UPDATE reduceri SET Marca=?, Model=?, An_Fabricatie=?, Culoare=?, Descriere=?, Pret_Zi=?, Pret_Redus=?, Tractiune=?, Consum=? WHERE ID_Masina=?";
                    ps=conn.prepareStatement(UptadeQuery);
                    ps.setString(1, marca.getText());
                    ps.setString(2, model.getText());
                    ps.setString(3, anfabricatie.getText());
                    ps.setString(4, culoare.getText());
                    ps.setString(5, descriere.getText());
                    ps.setString(6, pretzi.getText());
                    ps.setString(7, pretzi1.getText());
                    ps.setString(8, (String) tractiune.getSelectedItem());
                    ps.setString(9, consum.getText());
                    ps.setInt(10,Integer.parseInt(ID.getText()));
                    ps.executeUpdate();
                    Show_Products_In_JTable();
                    JOptionPane.showMessageDialog(null, "Masina A Fost Actualizata!");
                    clearFields();
                } catch (Exception ex) {
                    Logger.getLogger(AdaugatiAutomobil.class.getName()).log(Level.SEVERE, null, ex);
                }

                //update cu imagine
            }else{
                try{
                    InputStream img=new FileInputStream(new File(ImgPath));
                    UptadeQuery="UPDATE reduceri SET Marca=?, Model=?, An_Fabricatie=?, Culoare=?, Descriere=?, Pret_Zi=?, Pret_Redus=?, Tractiune=?, Consum=?, Poza=? WHERE ID_Masina=?";
                    ps=conn.prepareStatement(UptadeQuery);
                    ps.setString(1, marca.getText());
                    ps.setString(2, model.getText());
                    ps.setString(3, anfabricatie.getText());
                    ps.setString(4, culoare.getText());
                    ps.setString(5, descriere.getText());
                    ps.setString(6, pretzi.getText());
                    ps.setString(7, pretzi1.getText());
                    ps.setString(8, (String) tractiune.getSelectedItem());
                    ps.setString(9, consum.getText());
                    ps.setBlob(10, img);
                    ps.setInt(11,Integer.parseInt(ID.getText()));
                    ps.executeUpdate();
                    Show_Products_In_JTable();
                    JOptionPane.showMessageDialog(null, "Masina A Fost Actualizata!");

                    clearFields();
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null,ex.getMessage());
                }
            }

        }else
        {
            JOptionPane.showMessageDialog(null,"Unul sau mau multe câmpuri sunt goale!");
        }
    }//GEN-LAST:event_actualizatiActionPerformed

    private void stergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stergeActionPerformed
        // TODO add your handling code here:
        if(!ID.getText().equals(""))
        {
            try {
                Connection conn=getConnection();
                PreparedStatement ps=conn.prepareStatement("DELETE FROM reduceri WHERE ID_Masina=?");
                int id=Integer.parseInt(ID.getText());
                ps.setInt(1, id);
                ps.executeUpdate();
                Show_Products_In_JTable();
                JOptionPane.showMessageDialog(null,"Masina a fost ștearsă!");
                clearFields();
            } catch (SQLException ex) {
                Logger.getLogger(AdaugatiAutomobil.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"Masina nu a fost stearsă!");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Masina nu a fost stearsă : Nu se șterge id-ul!");
        }

    }//GEN-LAST:event_stergeActionPerformed
       
    //Afisarea datelor in Tabla
     //         1 -- Umplerea listei cu datele
     public ArrayList<GetteriReduceriMasini> getMasiniList(){
        
            ArrayList<GetteriReduceriMasini> reducerimasiniList=new ArrayList<GetteriReduceriMasini>();
            Connection conn=getConnection();
            String query="SELECT * FROM reduceri";
            
            Statement st;
            ResultSet rs;
            try {
            st=conn.createStatement();
            rs=st.executeQuery(query);
            GetteriReduceriMasini product;
            
            while(rs.next())
            {
                product=new GetteriReduceriMasini(rs.getInt("ID_Masina"),rs.getString("Marca"),rs.getString("Model"),rs.getInt("An_Fabricatie"),rs.getString("Culoare"),rs.getString("Descriere"),Float.parseFloat(rs.getString("Pret_Zi")),Float.parseFloat(rs.getString("Pret_Redus")), rs.getString("Tractiune"),rs.getString("Consum"),rs.getBytes("Poza"));
                reducerimasiniList.add(product);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VizualizareAutomobile.class.getName()).log(Level.SEVERE, null, ex);
        }
         return reducerimasiniList;
     }
     //         2 -- Popularea Tablei
     public void Show_Products_In_JTable(){
         ArrayList<GetteriReduceriMasini> list=getMasiniList();
         DefaultTableModel model=(DefaultTableModel)pretredus.getModel();
         
         
         model.setRowCount(0);
         Object[] row=new Object[10];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getID();
            row[1]=list.get(i).getmarca();
            row[2]=list.get(i).getmodel();
            row[3]=list.get(i).getanFabricatie();
            row[4]=list.get(i).getculoare();
            row[5]=list.get(i).getdescriere();
            row[6]=list.get(i).getpretZi();
            row[7]=list.get(i).getpretRedus();
            row[8]=list.get(i).gettractiune();
            row[9]=list.get(i).getconsum();
            
            model.addRow(row);
        }  
         
     }
     
     public void ShowItem(int index){
         ID.setText(Integer.toString(getMasiniList().get(index).getID()));
         marca.setText(getMasiniList().get(index).getmarca());
         model.setText(getMasiniList().get(index).getmodel());
         anfabricatie.setText(Integer.toString(getMasiniList().get(index).getanFabricatie()));
         culoare.setText(getMasiniList().get(index).getculoare());
         descriere.setText(getMasiniList().get(index).getdescriere());
         pretzi.setText(Float.toString(getMasiniList().get(index).getpretZi()));
         pretzi1.setText(Float.toString(getMasiniList().get(index).getpretZi()));
         tractiune.setSelectedItem(getMasiniList().get(index).gettractiune());
         consum.setText(getMasiniList().get(index).getconsum());
         imagine.setIcon(ResizeImage(null,getMasiniList().get(index).getimagine())); 
          
     }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReduceriAutomobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReduceriAutomobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReduceriAutomobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReduceriAutomobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReduceriAutomobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JButton actualizati;
    private javax.swing.JButton adaugareImagine;
    private javax.swing.JButton adaugate;
    private javax.swing.JTextField anfabricatie;
    private javax.swing.JTextField consum;
    private javax.swing.JTextField culoare;
    private javax.swing.JTextArea descriere;
    private javax.swing.JLabel imagine;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField model;
    private javax.swing.JLabel poza;
    private javax.swing.JTable pretredus;
    private javax.swing.JTextField pretzi;
    private javax.swing.JTextField pretzi1;
    private javax.swing.JButton sterge;
    private javax.swing.JComboBox tractiune;
    // End of variables declaration//GEN-END:variables
}
